[package]
name = "tactician"
version = "0.0.1"
authors = [ "Scott Ostler" ]

[profile.release]
panic = "abort"

[profile.dev]
panic = "abort"

[dependencies]
getopts = "0.2.*"
itertools = "0.7.*"
lazy_static = "1.0"
rand = "0.4.*"
